### ISSUE TITLE
Error on Multiple Summernote

### ISSUE THREAD

**Issue by matasoy** [StudioJunkyard/summernote-video-attributes#17]
There are 3 summernotes on my page. Using summernote@0.9.0 there is no child element on options. consol down there.

Cannot read properties of undefined (reading 'videoUrls')
    at videoAttributes.initialize (summernote-video-attributes.js:85:43)
    at t.value (summernote.min.js:2:19915)
    at summernote.min.js:2:18455
    at Array.forEach (<anonymous>)
    at t.value (summernote.min.js:2:18432)
    at t.value (summernote.min.js:2:17710)
    at new t (summernote.min.js:2:17597)
    at HTMLTextAreaElement.<anonymous> (summernote.min.js:2:23755)
    at Function.each (jquery-3.5.1.min.js:2:2976)
    at S.each (jquery-3.5.1.min.js:2:1454)
    
OPTION  CONSOLE  
```

{
    "showVideoSize": true,
    "showVideoAlignment": true,
    "showSuggestedVideos": true,
    "showPlayerControls": true,
    "showAutoplay": true,
    "showLoop": true,
    "icon": "<i class=\"note-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 14 14\" width=\"14\" height=\"14\"><path d=\"m 12.503106,4.03105 -3.087752,0 -0.09237,-0.72049 c 0,-0.41163 -0.333714,-0.74534 -0.745341,-0.74534 l -3.180124,0 c -0.411628,0 -0.745342,0.33372 -0.745342,0.74534 l -0.09237,0.72049 -3.062907,0 C 1.22246,4.03105 1,4.24109 1,4.51553 l 0,6.40993 c 0,0.27444 0.22246,0.50932 0.496894,0.50932 l 11.006212,0 C 12.77754,11.43478 13,11.1999 13,10.92546 L 13,4.51553 C 13,4.24109 12.77754,4.03105 12.503106,4.03105 Z M 7.00236,10.77794 c -1.687652,0 -3.055751,-1.3681 -3.055751,-3.05573 0,-1.68765 1.368099,-3.05574 3.055751,-3.05574 1.687652,0 3.055752,1.3681 3.055752,3.05574 0,1.6876 -1.3681,3.05573 -3.055752,3.05573 z m 5.426211,-5.43012 -2.608695,0 0,-0.77017 2.608695,0 0,0.77017 z M 8.876472,7.71575 A 1.8687454,1.8687454 0 0 1 7.007727,9.58449 1.8687454,1.8687454 0 0 1 5.138981,7.71575 1.8687454,1.8687454 0 0 1 7.007727,5.84701 1.8687454,1.8687454 0 0 1 8.876472,7.71575 Z\"/></svg></i>",
    "langInfo": {
        "font": {
            "bold": "Bold",
            "italic": "Italic",
            "underline": "Underline",
            "clear": "Remove Font Style",
            "height": "Line Height",
            "name": "Font Family",
            "strikethrough": "Strikethrough",
            "subscript": "Subscript",
            "superscript": "Superscript",
            "size": "Font Size",
            "sizeunit": "Font Size Unit"
        },
        "image": {
            "image": "Picture",
            "insert": "Insert Image",
            "resizeFull": "Resize full",
            "resizeHalf": "Resize half",
            "resizeQuarter": "Resize quarter",
            "resizeNone": "Original size",
            "floatLeft": "Float Left",
            "floatRight": "Float Right",
            "floatNone": "Remove float",
            "shapeRounded": "Shape: Rounded",
            "shapeCircle": "Shape: Circle",
            "shapeThumbnail": "Shape: Thumbnail",
            "shapeNone": "Shape: None",
            "dragImageHere": "Drag image or text here",
            "dropImage": "Drop image or Text",
            "selectFromFiles": "Select from files",
            "maximumFileSize": "Maximum file size",
            "maximumFileSizeError": "Maximum file size exceeded.",
            "url": "Image URL",
            "remove": "Remove Image",
            "original": "Original"
        },
        "video": {
            "video": "Video",
            "videoLink": "Video Link",
            "insert": "Insert Video",
            "url": "Video URL",
            "providers": "(YouTube, Google Drive, Vimeo, Vine, Instagram, DailyMotion, Youku, Peertube)"
        },
        "link": {
            "link": "Link",
            "insert": "Insert Link",
            "unlink": "Unlink",
            "edit": "Edit",
            "textToDisplay": "Text to display",
            "url": "To what URL should this link go?",
            "openInNewWindow": "Open in new window"
        },
        "table": {
            "table": "Table",
            "addRowAbove": "Add row above",
            "addRowBelow": "Add row below",
            "addColLeft": "Add column left",
            "addColRight": "Add column right",
            "delRow": "Delete row",
            "delCol": "Delete column",
            "delTable": "Delete table"
        },
        "hr": {
            "insert": "Insert Horizontal Rule"
        },
        "style": {
            "style": "Style",
            "p": "Normal",
            "blockquote": "Quote",
            "pre": "Code",
            "h1": "Header 1",
            "h2": "Header 2",
            "h3": "Header 3",
            "h4": "Header 4",
            "h5": "Header 5",
            "h6": "Header 6"
        },
        "lists": {
            "unordered": "Unordered list",
            "ordered": "Ordered list"
        },
        "options": {
            "help": "Help",
            "fullscreen": "Full Screen",
            "codeview": "Code View"
        },
        "paragraph": {
            "paragraph": "Paragraph",
            "outdent": "Outdent",
            "indent": "Indent",
            "left": "Align left",
            "center": "Align center",
            "right": "Align right",
            "justify": "Justify full"
        },
        "color": {
            "recent": "Recent Color",
            "more": "More Color",
            "background": "Background Color",
            "foreground": "Text Color",
            "transparent": "Transparent",
            "setTransparent": "Set transparent",
            "reset": "Reset",
            "resetToDefault": "Reset to default",
            "cpSelect": "Select"
        },
        "shortcut": {
            "shortcuts": "Keyboard shortcuts",
            "close": "Close",
            "textFormatting": "Text formatting",
            "action": "Action",
            "paragraphFormatting": "Paragraph formatting",
            "documentStyle": "Document Style",
            "extraKeys": "Extra keys"
        },
        "help": {
            "escape": "Escape",
            "insertParagraph": "Insert Paragraph",
            "undo": "Undo the last command",
            "redo": "Redo the last command",
            "tab": "Tab",
            "untab": "Untab",
            "bold": "Set a bold style",
            "italic": "Set a italic style",
            "underline": "Set a underline style",
            "strikethrough": "Set a strikethrough style",
            "removeFormat": "Clean a style",
            "justifyLeft": "Set left align",
            "justifyCenter": "Set center align",
            "justifyRight": "Set right align",
            "justifyFull": "Set full align",
            "insertUnorderedList": "Toggle unordered list",
            "insertOrderedList": "Toggle ordered list",
            "outdent": "Outdent on current paragraph",
            "indent": "Indent on current paragraph",
            "formatPara": "Change current block's format as a paragraph(P tag)",
            "formatH1": "Change current block's format as H1",
            "formatH2": "Change current block's format as H2",
            "formatH3": "Change current block's format as H3",
            "formatH4": "Change current block's format as H4",
            "formatH5": "Change current block's format as H5",
            "formatH6": "Change current block's format as H6",
            "insertHorizontalRule": "Insert horizontal rule",
            "linkDialog.show": "Show Link Dialog"
        },
        "history": {
            "undo": "Undo",
            "redo": "Redo"
        },
        "specialChar": {
            "specialChar": "SPECIAL CHARACTERS",
            "select": "Select Special characters"
        },
        "output": {
            "noSelection": "No Selection Made!"
        },
        "captionIt": {
            "tooltip": "Caption It"
        },
        "pagebreak": {
            "tooltip": "Page Break"
        },
        "videoAttributes": {
            "dialogTitle": "Video Attributes",
            "tooltip": "Video Attributes",
            "pluginTitle": "Video Attributes",
            "href": "URL",
            "videoSize": "Video size",
            "videoOption0": "Responsive",
            "videoOption1": "1280x720",
            "videoOption2": "853x480",
            "videoOption3": "640x360",
            "videoOption4": "560x315",
            "alignment": "Alignment",
            "alignmentOption0": "None",
            "alignmentOption1": "Left",
            "alignmentOption2": "Right",
            "alignmentOption3": "Initial",
            "alignmentOption4": "Inherit",
            "suggested": "Show Suggested videos when the video finishes",
            "controls": "Show player controls",
            "autoplay": "Autoplay",
            "loop": "Loop",
            "note": "Note: Not all options are available with all services...",
            "ok": "OK"
        }
    },
    "editing": true,
    "modules": {},
    "buttons": {},
    "lang": "en-US",
    "followingToolbar": false,
    "toolbarPosition": "top",
    "otherStaticBar": "",
    "codeviewKeepButton": false,
    "toolbar": [
        [
            "pagebreak",
            [
                "pagebreak"
            ]
        ],
        [
            "style",
            [
                "style"
            ]
        ],
        [
            "font",
            [
                "bold",
                "italic",
                "underline",
                "clear"
            ]
        ],
        [
            "fontname",
            [
                "fontname"
            ]
        ],
        [
            "color",
            [
                "color"
            ]
        ],
        [
            "para",
            [
                "ul",
                "ol",
                "paragraph"
            ]
        ],
        [
            "height",
            [
                "height"
            ]
        ],
        [
            "table",
            [
                "table"
            ]
        ],
        [
            "insert",
            [
                "videoAttributes",
                "media",
                "picture",
                "link",
                "hr",
                "video"
            ]
        ],
        [
            "view",
            [
                "fullscreen",
                "codeview"
            ]
        ]
    ],
    "popatmouse": true,
    "popover": {
        "image": [
            [
                "custom",
                [
                    "captionIt"
                ]
            ],
            [
                "imagesize",
                [
                    "imageSize100",
                    "imageSize50",
                    "imageSize25"
                ]
            ],
            [
                "float",
                [
                    "floatLeft",
                    "floatRight",
                    "floatNone"
                ]
            ],
            [
                "remove",
                [
                    "removeMedia"
                ]
            ]
        ]
    },
    "linkAddNoReferrer": false,
    "addLinkNoOpener": false,
    "airMode": false,
    "overrideContextMenu": false,
    "width": null,
    "height": 920,
    "linkTargetBlank": true,
    "focus": true,
    "tabDisable": false,
    "tabSize": 4,
    "styleWithCSS": false,
    "shortcuts": true,
    "textareaAutoSync": true,
    "tooltip": true,
    "container": {
        "0": {},
        "length": 1
    },
    "maxTextLength": 0,
    "blockquoteBreakingLevel": 2,
    "spellCheck": true,
    "disableGrammar": false,
    "placeholder": null,
    "inheritPlaceholder": false,
    "recordEveryKeystroke": false,
    "historyLimit": 200,
    "showDomainOnlyForAutolink": false,
    "hintMode": "word",
    "hintSelect": "after",
    "hintDirection": "bottom",
    "styleTags": [
        "p",
        "blockquote",
        "pre",
        "h1",
        "h2",
        "h3",
        "h4",
        "h5",
        "h6"
    ],
    "fontNames": [
        "Arial",
        "Arial Black",
        "Comic Sans MS",
        "Courier New",
        "Helvetica Neue",
        "Helvetica",
        "Impact",
        "Lucida Grande",
        "Tahoma",
        "Times New Roman",
        "Verdana"
    ],
    "fontNamesIgnoreCheck": [],
    "addDefaultFonts": true,
    "fontSizes": [
        "8",
        "9",
        "10",
        "11",
        "12",
        "14",
        "18",
        "24",
        "36"
    ],
    "fontSizeUnits": [
        "px",
        "pt"
    ],
    "colors": [
        [
            "#000000",
            "#424242",
            "#636363",
            "#9C9C94",
            "#CEC6CE",
            "#EFEFEF",
            "#F7F7F7",
            "#FFFFFF"
        ],
        [
            "#FF0000",
            "#FF9C00",
            "#FFFF00",
            "#00FF00",
            "#00FFFF",
            "#0000FF",
            "#9C00FF",
            "#FF00FF"
        ],
        [
            "#F7C6CE",
            "#FFE7CE",
            "#FFEFC6",
            "#D6EFD6",
            "#CEDEE7",
            "#CEE7F7",
            "#D6D6E7",
            "#E7D6DE"
        ],
        [
            "#E79C9C",
            "#FFC69C",
            "#FFE79C",
            "#B5D6A5",
            "#A5C6CE",
            "#9CC6EF",
            "#B5A5D6",
            "#D6A5BD"
        ],
        [
            "#E76363",
            "#F7AD6B",
            "#FFD663",
            "#94BD7B",
            "#73A5AD",
            "#6BADDE",
            "#8C7BC6",
            "#C67BA5"
        ],
        [
            "#CE0000",
            "#E79439",
            "#EFC631",
            "#6BA54A",
            "#4A7B8C",
            "#3984C6",
            "#634AA5",
            "#A54A7B"
        ],
        [
            "#9C0000",
            "#B56308",
            "#BD9400",
            "#397B21",
            "#104A5A",
            "#085294",
            "#311873",
            "#731842"
        ],
        [
            "#630000",
            "#7B3900",
            "#846300",
            "#295218",
            "#083139",
            "#003163",
            "#21104A",
            "#4A1031"
        ]
    ],
    "colorsName": [
        [
            "Black",
            "Tundora",
            "Dove Gray",
            "Star Dust",
            "Pale Slate",
            "Gallery",
            "Alabaster",
            "White"
        ],
        [
            "Red",
            "Orange Peel",
            "Yellow",
            "Green",
            "Cyan",
            "Blue",
            "Electric Violet",
            "Magenta"
        ],
        [
            "Azalea",
            "Karry",
            "Egg White",
            "Zanah",
            "Botticelli",
            "Tropical Blue",
            "Mischka",
            "Twilight"
        ],
        [
            "Tonys Pink",
            "Peach Orange",
            "Cream Brulee",
            "Sprout",
            "Casper",
            "Perano",
            "Cold Purple",
            "Careys Pink"
        ],
        [
            "Mandy",
            "Rajah",
            "Dandelion",
            "Olivine",
            "Gulf Stream",
            "Viking",
            "Blue Marguerite",
            "Puce"
        ],
        [
            "Guardsman Red",
            "Fire Bush",
            "Golden Dream",
            "Chelsea Cucumber",
            "Smalt Blue",
            "Boston Blue",
            "Butterfly Bush",
            "Cadillac"
        ],
        [
            "Sangria",
            "Mai Tai",
            "Buddha Gold",
            "Forest Green",
            "Eden",
            "Venice Blue",
            "Meteorite",
            "Claret"
        ],
        [
            "Rosewood",
            "Cinnamon",
            "Olive",
            "Parsley",
            "Tiber",
            "Midnight Blue",
            "Valentino",
            "Loulou"
        ]
    ],
    "colorButton": {
        "foreColor": "#000000",
        "backColor": "#FFFF00"
    },
    "lineHeights": [
        "1.0",
        "1.2",
        "1.4",
        "1.5",
        "1.6",
        "1.8",
        "2.0",
        "3.0"
    ],
    "tableClassName": "table table-bordered",
    "insertTableMaxSize": {
        "col": 10,
        "row": 10
    },
    "dialogsInBody": false,
    "dialogsFade": false,
    "maximumImageFileSize": null,
    "acceptImageFileTypes": "image/*",
    "allowClipboardImagePasting": true,
    "callbacks": {},
    "codemirror": {
        "mode": "text/html",
        "htmlMode": true,
        "lineNumbers": true
    },
    "codeviewFilter": true,
    "codeviewFilterRegex": {},
    "codeviewIframeFilter": true,
    "codeviewIframeWhitelistSrc": [],
    "codeviewIframeWhitelistSrcBase": [
        "www.youtube.com",
        "www.youtube-nocookie.com",
        "www.facebook.com",
        "vine.co",
        "instagram.com",
        "player.vimeo.com",
        "www.dailymotion.com",
        "player.youku.com",
        "jumpingbean.tv",
        "v.qq.com"
    ],
    "keyMap": {
        "pc": {
            "ESC": "escape",
            "ENTER": "insertParagraph",
            "CTRL+Z": "undo",
            "CTRL+Y": "redo",
            "TAB": "tab",
            "SHIFT+TAB": "untab",
            "CTRL+B": "bold",
            "CTRL+I": "italic",
            "CTRL+U": "underline",
            "CTRL+SHIFT+S": "strikethrough",
            "CTRL+BACKSLASH": "removeFormat",
            "CTRL+SHIFT+L": "justifyLeft",
            "CTRL+SHIFT+E": "justifyCenter",
            "CTRL+SHIFT+R": "justifyRight",
            "CTRL+SHIFT+J": "justifyFull",
            "CTRL+SHIFT+NUM7": "insertUnorderedList",
            "CTRL+SHIFT+NUM8": "insertOrderedList",
            "CTRL+LEFTBRACKET": "outdent",
            "CTRL+RIGHTBRACKET": "indent",
            "CTRL+NUM0": "formatPara",
            "CTRL+NUM1": "formatH1",
            "CTRL+NUM2": "formatH2",
            "CTRL+NUM3": "formatH3",
            "CTRL+NUM4": "formatH4",
            "CTRL+NUM5": "formatH5",
            "CTRL+NUM6": "formatH6",
            "CTRL+ENTER": "insertHorizontalRule",
            "CTRL+K": "linkDialog.show"
        },
        "mac": {
            "ESC": "escape",
            "ENTER": "insertParagraph",
            "CMD+Z": "undo",
            "CMD+SHIFT+Z": "redo",
            "TAB": "tab",
            "SHIFT+TAB": "untab",
            "CMD+B": "bold",
            "CMD+I": "italic",
            "CMD+U": "underline",
            "CMD+SHIFT+S": "strikethrough",
            "CMD+BACKSLASH": "removeFormat",
            "CMD+SHIFT+L": "justifyLeft",
            "CMD+SHIFT+E": "justifyCenter",
            "CMD+SHIFT+R": "justifyRight",
            "CMD+SHIFT+J": "justifyFull",
            "CMD+SHIFT+NUM7": "insertUnorderedList",
            "CMD+SHIFT+NUM8": "insertOrderedList",
            "CMD+LEFTBRACKET": "outdent",
            "CMD+RIGHTBRACKET": "indent",
            "CMD+NUM0": "formatPara",
            "CMD+NUM1": "formatH1",
            "CMD+NUM2": "formatH2",
            "CMD+NUM3": "formatH3",
            "CMD+NUM4": "formatH4",
            "CMD+NUM5": "formatH5",
            "CMD+NUM6": "formatH6",
            "CMD+ENTER": "insertHorizontalRule",
            "CMD+K": "linkDialog.show"
        }
    },
    "icons": {
        "align": "note-icon-align",
        "alignCenter": "note-icon-align-center",
        "alignJustify": "note-icon-align-justify",
        "alignLeft": "note-icon-align-left",
        "alignRight": "note-icon-align-right",
        "rowBelow": "note-icon-row-below",
        "colBefore": "note-icon-col-before",
        "colAfter": "note-icon-col-after",
        "rowAbove": "note-icon-row-above",
        "rowRemove": "note-icon-row-remove",
        "colRemove": "note-icon-col-remove",
        "indent": "note-icon-align-indent",
        "outdent": "note-icon-align-outdent",
        "arrowsAlt": "note-icon-arrows-alt",
        "bold": "note-icon-bold",
        "caret": "note-icon-caret",
        "circle": "note-icon-circle",
        "close": "note-icon-close",
        "code": "note-icon-code",
        "eraser": "note-icon-eraser",
        "floatLeft": "note-icon-float-left",
        "floatRight": "note-icon-float-right",
        "font": "note-icon-font",
        "frame": "note-icon-frame",
        "italic": "note-icon-italic",
        "link": "note-icon-link",
        "unlink": "note-icon-chain-broken",
        "magic": "note-icon-magic",
        "menuCheck": "note-icon-menu-check",
        "minus": "note-icon-minus",
        "orderedlist": "note-icon-orderedlist",
        "pencil": "note-icon-pencil",
        "picture": "note-icon-picture",
        "question": "note-icon-question",
        "redo": "note-icon-redo",
        "rollback": "note-icon-rollback",
        "square": "note-icon-square",
        "strikethrough": "note-icon-strikethrough",
        "subscript": "note-icon-subscript",
        "superscript": "note-icon-superscript",
        "table": "note-icon-table",
        "textHeight": "note-icon-text-height",
        "trash": "note-icon-trash",
        "underline": "note-icon-underline",
        "undo": "note-icon-undo",
        "unorderedlist": "note-icon-unorderedlist",
        "video": "note-icon-video"
    },
    "captionIt": {
        "figureClass": "{figure-class/es}",
        "figcaptionClass": "{figcapture-class/es}",
        "captionText": "Şekil 1. Resim Yazısı"
    },
    "pagebreak": {
        "icon": "<i class=\"note-icon\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 14 14\" width=\"14\" height=\"14\"><path d=\"M 4,5.5 4,1 l 9,0 0,4.5 -0.750612,0 0,-3.74939 -7.498776,0 0,3.75061 L 4,5.50122 Z M 13,7.75061 13,13 4,13 4,7.75061 l 0.750612,0 0,4.5 7.5,0 0,-4.5 0.749388,0 z m -6,-1.5 1.5,0 L 8.5,7 7,7 7,6.25061 Z m -2.249388,0 1.5,0 0,0.74939 -1.5,0 0,-0.74939 z m 4.5,0 1.5,0 0,0.74939 -1.5,0 0,-0.74939 z m 2.249388,0 1.5,0 L 13,7 11.5,7 11.5,6.25061 Z M 1,4.37469 3.250612,6.62531 1,8.87469 l 0,-4.5 z\"/></svg></i>",
        "css": "@media all{.note-editable .page-break{position:relative;display:block;width:100%;height:1px;background-color:#ddd;margin:15px 0;}.note-editable .page-break:after{content:\"Page-Break\";position:absolute;width:100%;height:20px;top:-10px;color:#ddd;-webkit-text-shadow:0 0 5px #fff,0 0 5px #fff,0 0 5px #fff,0 0 5px #fff;-moz-text-shadow:0 0 5px #fff,0 0 5px #fff,0 0 5px #fff,0 0 5px #fff;text-shadow:0 0 5px #fff,0 0 5px #fff,0 0 5px #fff,0 0 5px #fff;text-align:center;}}@media print{.note-editable .page-break{display:block;page-break-before:always;}}"
    },
    "minHeight": null,
    "maxHeight": null,
    "id": "17282101453291"
}
```

**Comment by johnreaume** [comment]
matasoy,

I'm not part of the support team, but also had the same issue as you 
It's caused by this plugin being out of date with v.0.9 of summernote

I made the changes, and just passing along my updated code

[summernote-video-attributes.js](https://github.com/user-attachments/files/22977243/summernote-video-attributes.js)
